### ISSUE TITLE
where store videojs plugin package?

### ISSUE THREAD

**Issue by mostafa6765** [videojs/generator-videojs-plugin#161]
I am familiar with vue , react cli but videojs plugin cli so amazing I can't get plugin folder.

**Comment by misteroneill** [comment]
Can you clarify what you mean by "can't get plugin folder"? It's unclear what your issue is.

This is a Yeoman generator which you'd usually run in an empty folder to start a project. It will output a bunch of files into whatever folder it's run in.

If it's any help, this project's [README has a helpful "Getting Started" section](https://github.com/videojs/generator-videojs-plugin/blob/master/README.md#getting-started), which also points to [the Yeoman "Getting Started" page](http://yeoman.io/learning/index.html), in case you're unfamiliar with that tool.

**Comment by mostafa6765** [comment]
After installing videojs with cli yeoman don't make a plugin folder as `plugin-name` .
