### ISSUE TITLE
ES modules are not being sufficiently transpiled before publish

### ISSUE THREAD

**Issue by misteroneill** [videojs/generator-videojs-plugin#228]
See: https://github.com/brightcove/react-player-loader/issues/8

Seems that the ES module still has ES6 code in it.

**Comment by gkatsev** [comment]
It looks like @bebl/preset-env and browserslist don't have an uglify 2 target, which is basically what we need for minification to not fail in most cases. uglify 2 only supports ES5 and doesn't support *any* ES6 even if all our supported browsers do support the little ES6 that's left in the dist files.

**Comment by gkatsev** [comment]
We may only need to set `forcealltransforms` https://babeljs.io/docs/en/next/babel-preset-env.html#forcealltransforms

**Comment by misteroneill** [comment]
That would be ideal because it means updating the videojs-generate-rollup-config project and not all the consuming projects.

**Comment by misteroneill** [comment]
Does `forceAllTransforms` render the `browserslist` stuff irrelevant?

**Comment by gkatsev** [comment]
Not sure. I assume it works in conjunction and basically once it selected browsers it runs all transforms from that group of features rather than only what the browsers support. But I'm not sure that's it.

I.e., if browser X is selected and it supports ES5 and only a few features of ES6, all ES5 transforms would still be selected until browser X either drops below usage or is upgraded to support all of ES6 or something.

**Comment by misteroneill** [comment]
Seems like this was an issue related to a bad dependency version in the reporting project.
