### ISSUE TITLE
When bower is enabled the dist directory is not included in npm packages

### ISSUE THREAD

**Issue by hartman** [videojs/generator-videojs-plugin#24]
Normally, when you do `npm version && npm publish`, your dist ~~module~~ directory is included in the package. When you generated a package that has bower enabled, it seems that I'm not able to do that.

I need to do `npm version && npm run build && npm publish`.

**Comment by misteroneill** [comment]
Thanks for the report! I'll look into it.

**Comment by misteroneill** [comment]
@hartman This is odd because running `npm version` should cause a build to be run - it does on my machine - which `npm publish` should pick up. Are you running a full `version` command (e.g., `npm version major`)?

Also, make sure you're not on Windows because the Bower versioning bit won't work there (yet).

**Comment by hartman** [comment]
I used `npm version patch`

These were the produce github releases:
https://github.com/hartman/videojs-ogvjs/releases

At least most 1.0.* builds have this problem, for instance:
`http://registry.npmjs.org/videojs-ogvjs/-/videojs-ogvjs-1.0.5.tgz`

With 1.0.6 I did another npm build before the publish

`http://registry.npmjs.org/videojs-ogvjs/-/videojs-ogvjs-1.0.6.tgz`

Maybe it's because i used a prerelease version of the generator when I created this repo, but I was not able to find a difference that would explain a problem like this

I'm using npm version 2.14.12 on Mac OS X.

**Comment by misteroneill** [comment]
Alright, I realized what's happening here. The fancy Bower-friendly tagging process force-adds `dist/` to the repo specifically for the tagged commit and then rolls `master` back to the parent commit. This is where the trouble starts. Because `dist/` was added to the tagged commit, the roll back removes `dist/` _entirely_ from the file system (correctly).

The solution here is going to be exactly what you're doing @hartman: `"prepublish": "npm run build"`.

Thanks a ton for the report!
