### ISSUE TITLE
Run tests against dist files instead of bundling plugin.

### ISSUE THREAD

**Issue by misteroneill** [videojs/generator-videojs-plugin#57]
In an effort to ensure that the file(s) in `dist/` we are shipping are error-free, we should run unit tests against them instead of bundling the plugin with the tests via Browserify.

**Comment by gkatsev** [comment]
We get a lot of benefit and ease of use from using browserify for writing the tests and requiring each file individually. This also means that you can more easily test functions that aren't exposed directly but are available as modules.
I think the solution here is to have API-layer tests that run against the `dist/` output (could even run against a browserified output as well) that test just the boundary layer rather than doing *all* of the unit tests through this `dist/`.

**Comment by misteroneill** [comment]
Yeah, I agree. I think this was a @dmlap request. I'm not that concerned about the accuracy of unit tests not against the `dist/`.
