### ISSUE TITLE
Move browserify transforms to dependencies.

### ISSUE THREAD

**Issue by misteroneill** [videojs/generator-videojs-plugin#58]

**Comment by misteroneill** [comment]
I don't recall why this was added, but @gkatsev has your work on videojs.com shed any light on this?

**Comment by gkatsev** [comment]
It's because things like `browserify-shim` which currently run always are set as devDependencies but if it's being used through browserify directly, you'd want that transform to be installed as a dependency.
However, for browserify-shim itself, we want t to be a devDep and only run on files that belong in `dist/`.

**Comment by misteroneill** [comment]
Gotcha. So, transforms in dependencies except `browserify-shim`.

**Comment by gkatsev** [comment]
Unless we need to shim something else, in which case it'll be a lot more complicated...
I've actually gone ahead and made a few PRs for thing against videojs-playlist and videojs-contrib-hls already, at least the browserify-shim thing.
